### ISSUE TITLE
target_size=None  can not work.

### ISSUE THREAD

**Issue by kuixu** [MarvinTeichmann/tensorflow-fcn#16]
I found code about the input shape.
```
    if target_size:
        input_shape = target_size + (3,)
    else:
        input_shape = (None, None, 3)
```
When I set target_size=None, error encountered as below:
```
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    data_dir, label_dir, target_size=target_size, resume_training=True)
  File "train.py", line 102, in train
    batch_size=batch_size, shuffle=True
  File "/data/kuixu/exper/fcn/Keras-FCN/utils/SegDataGenerator.py", line 186, in flow_from_directory
    save_to_dir=save_to_dir, save_prefix=save_prefix, save_format=save_format)
  File "/data/kuixu/exper/fcn/Keras-FCN/utils/SegDataGenerator.py", line 26, in __init__
    self.target_size = tuple(target_size)
TypeError: 'NoneType' object is not iterable

```

please help

**Comment by MarvinTeichmann** [comment]
I cannot find the line you quoted in my code:

```
    if target_size:
        input_shape = target_size + (3,)
    else:
        input_shape = (None, None, 3)
```

Can you point me to the right direction?

**Comment by MarvinTeichmann** [comment]
Please reopen if you can provide a more elaborate problem description.
